### ISSUE TITLE
Is IE9 really supported?

### ISSUE THREAD

**Issue by drnkwati** [pseudosavant/psQuery#3]
I glanced through the source code and noticed 
the ajax function makes use of XMLHttpRequest which is not supported by IE9
So my question is IE9  supported

**Comment by pseudosavant** [comment]
I haven't tried IE9 in a while but last time I tested it it did work. XMLHTTPRequest v1 has been supported by IE since IE7, according to MDN: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest.

Paul
________________________________
